directory=..\\papRuntime

#operation:URL = folder & name of file as how response should be stored
#download to save responses
#fetch to read json files in offline
#autoDownload to download the responses based on the response for url configured

#download-/system/resourceManagers/T24/resources=resources\\T24Resources
#download-/system/resourceManagers/TAP/resources=resources\\TAPResources
download-/regression/saveIRFX/accounts/14613=resources\\accountOverview\\T24Account
download-/regression/saveIRFX/accounts/customer/100100=resources\\customerAccounts\\T24Customer

#fetch-/meta/resourceManagers/T24/resources=resources\\T24Resources
#fetch-/meta/resourceManagers/TAP/resources=resources\\TAPResources
#fetch-/meta/roles=roles
fetch-/regression/fetchIRFX/accounts/14613=resources\\accountOverview\\T24Account
fetch-/regression/fetchIRFX/accounts/customer/100100=resources\\customerAccounts\\T24Customer


#autoDownload-/system/resourceManagers/T24/resources=/system/resources/{resourceType}/{id}/attributes
#autoDownload-/system/resourceManagers/TAP/resources=/system/resources/{resourceType}/{id}/attributes
autoDownload-/regression/saveIRFX/accounts/customer/100100=/regression/saveIRFX/accounts/{Account}/balance
json=json
xacml=xacml
roles=roles