# ---------------------------------------------------------------------------
# Microservices Configuration File
# ---------------------------------------------------------------------------

# Property to indicate Context Routing or external HTTP call
isContextBasedRouting = false

connectionTimeout = 60

# Host URL configured for each of Microservices, to be configured in case isContextBasedRouting is set to false
MSHostUrl_getAccounts = http://localhost:9089/irf-provider-container/api
MSHostUrl_getAccountTransactions = http://localhost:9089/irf-provider-container/api
MSHostUrl_createPaymentOrder = http://localhost:9089/irf-provider-container/api

#SSL related configuration
ssl.keystore.path =
#To enable SSL store and key password, uncomment below configuration and add password in plain text
#ssl.store.password = ******
#ssl.key.password = ******

