RetryWait=60
RetryCount=4
ConnectionTimeout=120
# disabling the default credentials, to make IRISMETADATA queue as default for metadata request 
# t24.security.context=******/******
companyId = GB0010001

#timeout in milliseconds
#apiTimeOut=

TafcConnectionFactory=jca/t24ConnectionFactory

