#fusion.base.url=http://10.0.0.6:9095
fusion.base.url=https://finsetuisb.fusionfin.com
webclient.pool.max-connections=100
webclient.pool.idle-timeout-seconds=20
webclient.pool.life-time-seconds=600
webclient.connect-timeout-millis=5000
webclient.read-timeout-seconds=90
webclient.response-timeout-seconds=300

######## Customer Loan simulation and activation
fusion.customer.create.url=/fusionapi/api/v1.0.0/party/createCustomers/{id}
fusion.loan.simulation.create.url=/fusionapi/api/v1.0.0/product/createFusionSimulation
fusion.loan.simulation.update.url=/fusionapi/api/v1.0.0/product/modifyFusionSimulation/{id}
fusion.loan.detail.update.url=/fusionapi/api/v1.0.0/reference/create/fusionloandetails/{id}
fusion.loan.schedule.get.url=/fusionapi/api/v1.0.0/reference/fusion/loanResponse
fusion.loan.activation.put.url=/fusionapi/api/v1.0.0/product/fusion/aasimulationrunner/{id}
######Collection 
fusion.loan.collection.creation.post.url=/fusionapi/api/v1.0.0/reference/fusioncollectioncreation
fusion.loan.collection.response.get.url=/fusionapi/api/v1.0.0/reference/fusionCollectionResponse

#######PayOff
fusion.loan.payoff.creation.post.url=/fusionapi/api/v1.0.0/product/fusionPayoff
fusion.loan.payoff.response.get.url=/fusionapi/api/v1.0.0/reference/fusionloanpayoffdetail

########Settlement

fusion.loan.settlement.fullwaiveoff.post.url=/fusionapi/api/v1.0.0/party/Fusion/FullWaiveOff
fusion.loan.settlement.waiveoffstatus.post.url=/fusionapi/api/v1.0.0/party/Fusion/WaiveoffStatus

####delay
fusion.loan.schedule.delay.seconds=30
fusion.loan.schedule.delayPayOff.seconds=30