spring.application.name=fusionfinanceinterface
#spring.profiles.active=dev

 

#Logging
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.com.bct = DEBUG
spring.main.banner-mode=off
server.servlet.context-path=/fusionfinanceinterface


# Enable detailed logging for WebClient
logging.level.org.springframework.web.reactive.function.client.ExchangeFunctions=DEBUG
logging.level.org.springframework.web.reactive.function.client.ExchangeFilterFunctions=DEBUG
logging.level.reactor.netty.http.client=DEBUG
logging.level.reactor.netty.http.client.HttpClient=DEBUG
 
# External constant file
spring.config.import=classpath:api-constants.properties
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


 