RetryWait=60
RetryCount=4
ConnectionTimeout=120
# disabling the default credentials, to make IRISMETADATA queue as default for metadata request 
# t24.security.context=******/******
companyId = GB0010001


# set TRUE, to get success empty body response in case of path parameter passed in Enquiry api and record not returned from T24
# enquiryPathParamEmptySuccessResponse = TRUE

#timeout in milliseconds
#apiTimeOut=

#enable mdal.mode for mdal requests, allowed values: serialized, flattened
#mdal.mode=serialized
#allowed values: internal, external
#mdal-registry.mode =external
#mdal-registry.baseURL =http://localhost:8095/ms-genericconfig-api/api
#mdal-registry.URI =/v1.0.0/system/configurationGroups/{groupId}/configuration


#used this to get metadata if default is failed to get
#otherOperationalCompanyId= GB0010001

# set TRUE, to get Transact language Specific Error Messages
#languageSpecificErrorMessages = TRUE

tafj.runtime.earName=TAFJJEE_EAR

internal.ejb.beanName=IRISINTProcessingBean
external.ejb.beanName=IRISEXTProcessingBean
internal.activity.ejb.beanName=AAINTProcessingBean
external.activity.ejb.beanName=AAEXTProcessingBean
metadata.ejb.beanName=IRISMETADATAProcessingBean


#Enable the below checks respectively to restrict tags in request for security reasons
htmlTagsCheck=false
embeddedFunctionCallsCheck=false
htmlAttributesCheck=false
htmlEventsCheck=false
javascriptCheck=false
vbscriptCheck=false
alertCheck=false
evalCheck=false
expressionCheck=false