property.defaultPattern=%d{yyyy-MM-dd HH:mm:ss,SSS} [t=%t,p=%X{PID}] %-5p [%c{-1}] uuId="%X{uuId}", %m%n

property.filepath = ${env:LOG_HOME}

loggers=ALERT.UTIL,ALERT.MDC,DIAGNOSTIC.MDC,DIAGNOSTIC.UTIL,AUDIT.UTIL

logger.ALERT.UTIL.name=ALERT.UTIL
logger.ALERT.UTIL.level=ERROR
logger.ALERT.UTIL.additivity=false
logger.ALERT.UTIL.appenderRefs=rolling
logger.ALERT.UTIL.appenderRef.rolling.ref=rolling

logger.DIAGNOSTIC.UTIL.name=DIAGNOSTIC.UTIL
logger.DIAGNOSTIC.UTIL.level=ERROR
logger.DIAGNOSTIC.UTIL.additivity=false
logger.DIAGNOSTIC.UTIL.appenderRefs=rolling
logger.DIAGNOSTIC.UTIL.appenderRef.rolling.ref=rolling

logger.AUDIT.UTIL.name=AUDIT.UTIL
logger.AUDIT.UTIL.level=ERROR
logger.AUDIT.UTIL.additivity=false
logger.AUDIT.UTIL.appenderRefs=rolling
logger.AUDIT.UTIL.appenderRef.rolling.ref=rolling

logger.ALERT.MDC.name=ALERT.com.temenos.masterdata
logger.ALERT.MDC.level=ERROR
logger.ALERT.MDC.additivity=false
logger.ALERT.MDC.appenderRefs=rolling
logger.ALERT.MDC.appenderRef.rolling.ref=rolling

logger.DIAGNOSTIC.MDC.name=DIAGNOSTIC.com.temenos.masterdata
logger.DIAGNOSTIC.MDC.level=ERROR
logger.DIAGNOSTIC.MDC.additivity=false
logger.DIAGNOSTIC.MDC.appenderRefs=rolling
logger.DIAGNOSTIC.MDC.appenderRef.rolling.ref=rolling


appenders=console,rolling

appender.console.type=Console
appender.console.name=STDOUT
appender.console.layout.type=PatternLayout
appender.console.layout.pattern=${defaultPattern}

# This below lines are used to push our logs in to grafana dashboard
# Valid portId need to be passed for rolling.host

#appender.rolling.type = socket
#appender.rolling.name = rolling
#appender.rolling.port = 4560
#appender.rolling.host = localhost
#appender.rolling.reconnectionDelayMillis = 5000
#appender.rolling.encoding = UTF-8
#appender.rolling.layout.type = PatternLayout
#appender.rolling.layout.pattern = uuId=%X{uuId},%m%n
 
# The below lines are used to write our logs in the file

appender.rolling.type = RollingFile
appender.rolling.name = rolling
appender.rolling.fileName = ${filepath}/irisLogs/iris.log
appender.rolling.filePattern = ${filepath}/irisLogs/iris-%i.log
appender.rolling.layout.type = PatternLayout
appender.rolling.layout.pattern = ${defaultPattern}
appender.rolling.policies.type = Policies
appender.rolling.policies.size.type = SizeBasedTriggeringPolicy
appender.rolling.policies.size.size=250MB
appender.rolling.strategy.type = DefaultRolloverStrategy
appender.rolling.strategy.max = 20